server:
  port: 8085

logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
    web: info
    ru.neoflex.deal.feign: debug

deal:
  url: 'http://localhost:8082/deal'
statement:
  url: 'http://localhost:8083/statement'