rate: 19.00
insurance_rate: 5.00

logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
    web: info
